/* ============================================================================
   PAÍSES — código de discagem (DDI) para o seletor de WhatsApp internacional.
   A bandeira é renderizada pelo componente Flag (lib flag-icons, SVG) a
   partir do código ISO 3166-1 alpha-2 — emoji de bandeira não é confiável
   (Windows não tem os glifos, só mostra a sigla).
   Brasil vem primeiro por ser o padrão do formulário.
   ========================================================================= */

export const PAISES = [
  { name: 'Brasil', code: 'BR', dial: '55' },

  // América
  { name: 'Argentina', code: 'AR', dial: '54' },
  { name: 'Bahamas', code: 'BS', dial: '1' },
  { name: 'Barbados', code: 'BB', dial: '1' },
  { name: 'Belize', code: 'BZ', dial: '501' },
  { name: 'Bolívia', code: 'BO', dial: '591' },
  { name: 'Canadá', code: 'CA', dial: '1' },
  { name: 'Chile', code: 'CL', dial: '56' },
  { name: 'Colômbia', code: 'CO', dial: '57' },
  { name: 'Costa Rica', code: 'CR', dial: '506' },
  { name: 'Cuba', code: 'CU', dial: '53' },
  { name: 'Equador', code: 'EC', dial: '593' },
  { name: 'El Salvador', code: 'SV', dial: '503' },
  { name: 'Estados Unidos', code: 'US', dial: '1' },
  { name: 'Guatemala', code: 'GT', dial: '502' },
  { name: 'Guiana', code: 'GY', dial: '592' },
  { name: 'Guiana Francesa', code: 'GF', dial: '594' },
  { name: 'Haiti', code: 'HT', dial: '509' },
  { name: 'Honduras', code: 'HN', dial: '504' },
  { name: 'Jamaica', code: 'JM', dial: '1' },
  { name: 'México', code: 'MX', dial: '52' },
  { name: 'Nicarágua', code: 'NI', dial: '505' },
  { name: 'Panamá', code: 'PA', dial: '507' },
  { name: 'Paraguai', code: 'PY', dial: '595' },
  { name: 'Peru', code: 'PE', dial: '51' },
  { name: 'Porto Rico', code: 'PR', dial: '1' },
  { name: 'República Dominicana', code: 'DO', dial: '1' },
  { name: 'Suriname', code: 'SR', dial: '597' },
  { name: 'Trinidad e Tobago', code: 'TT', dial: '1' },
  { name: 'Uruguai', code: 'UY', dial: '598' },
  { name: 'Venezuela', code: 'VE', dial: '58' },

  // Europa
  { name: 'Alemanha', code: 'DE', dial: '49' },
  { name: 'Albânia', code: 'AL', dial: '355' },
  { name: 'Andorra', code: 'AD', dial: '376' },
  { name: 'Áustria', code: 'AT', dial: '43' },
  { name: 'Bélgica', code: 'BE', dial: '32' },
  { name: 'Bielorrússia', code: 'BY', dial: '375' },
  { name: 'Bósnia e Herzegovina', code: 'BA', dial: '387' },
  { name: 'Bulgária', code: 'BG', dial: '359' },
  { name: 'Croácia', code: 'HR', dial: '385' },
  { name: 'Dinamarca', code: 'DK', dial: '45' },
  { name: 'Eslováquia', code: 'SK', dial: '421' },
  { name: 'Eslovênia', code: 'SI', dial: '386' },
  { name: 'Espanha', code: 'ES', dial: '34' },
  { name: 'Estônia', code: 'EE', dial: '372' },
  { name: 'Finlândia', code: 'FI', dial: '358' },
  { name: 'França', code: 'FR', dial: '33' },
  { name: 'Grécia', code: 'GR', dial: '30' },
  { name: 'Hungria', code: 'HU', dial: '36' },
  { name: 'Irlanda', code: 'IE', dial: '353' },
  { name: 'Islândia', code: 'IS', dial: '354' },
  { name: 'Itália', code: 'IT', dial: '39' },
  { name: 'Kosovo', code: 'XK', dial: '383' },
  { name: 'Letônia', code: 'LV', dial: '371' },
  { name: 'Liechtenstein', code: 'LI', dial: '423' },
  { name: 'Lituânia', code: 'LT', dial: '370' },
  { name: 'Luxemburgo', code: 'LU', dial: '352' },
  { name: 'Macedônia do Norte', code: 'MK', dial: '389' },
  { name: 'Malta', code: 'MT', dial: '356' },
  { name: 'Moldávia', code: 'MD', dial: '373' },
  { name: 'Mônaco', code: 'MC', dial: '377' },
  { name: 'Montenegro', code: 'ME', dial: '382' },
  { name: 'Noruega', code: 'NO', dial: '47' },
  { name: 'Países Baixos', code: 'NL', dial: '31' },
  { name: 'Polônia', code: 'PL', dial: '48' },
  { name: 'Portugal', code: 'PT', dial: '351' },
  { name: 'Reino Unido', code: 'GB', dial: '44' },
  { name: 'República Tcheca', code: 'CZ', dial: '420' },
  { name: 'Romênia', code: 'RO', dial: '40' },
  { name: 'Rússia', code: 'RU', dial: '7' },
  { name: 'San Marino', code: 'SM', dial: '378' },
  { name: 'Sérvia', code: 'RS', dial: '381' },
  { name: 'Suécia', code: 'SE', dial: '46' },
  { name: 'Suíça', code: 'CH', dial: '41' },
  { name: 'Ucrânia', code: 'UA', dial: '380' },
  { name: 'Vaticano', code: 'VA', dial: '379' },

  // Ásia
  { name: 'Afeganistão', code: 'AF', dial: '93' },
  { name: 'Arábia Saudita', code: 'SA', dial: '966' },
  { name: 'Armênia', code: 'AM', dial: '374' },
  { name: 'Azerbaijão', code: 'AZ', dial: '994' },
  { name: 'Bahrein', code: 'BH', dial: '973' },
  { name: 'Bangladesh', code: 'BD', dial: '880' },
  { name: 'Brunei', code: 'BN', dial: '673' },
  { name: 'Butão', code: 'BT', dial: '975' },
  { name: 'Camboja', code: 'KH', dial: '855' },
  { name: 'Catar', code: 'QA', dial: '974' },
  { name: 'Cazaquistão', code: 'KZ', dial: '7' },
  { name: 'China', code: 'CN', dial: '86' },
  { name: 'Chipre', code: 'CY', dial: '357' },
  { name: 'Coreia do Norte', code: 'KP', dial: '850' },
  { name: 'Coreia do Sul', code: 'KR', dial: '82' },
  { name: 'Emirados Árabes Unidos', code: 'AE', dial: '971' },
  { name: 'Filipinas', code: 'PH', dial: '63' },
  { name: 'Geórgia', code: 'GE', dial: '995' },
  { name: 'Hong Kong', code: 'HK', dial: '852' },
  { name: 'Índia', code: 'IN', dial: '91' },
  { name: 'Indonésia', code: 'ID', dial: '62' },
  { name: 'Irã', code: 'IR', dial: '98' },
  { name: 'Iraque', code: 'IQ', dial: '964' },
  { name: 'Israel', code: 'IL', dial: '972' },
  { name: 'Japão', code: 'JP', dial: '81' },
  { name: 'Jordânia', code: 'JO', dial: '962' },
  { name: 'Kuwait', code: 'KW', dial: '965' },
  { name: 'Laos', code: 'LA', dial: '856' },
  { name: 'Líbano', code: 'LB', dial: '961' },
  { name: 'Macau', code: 'MO', dial: '853' },
  { name: 'Malásia', code: 'MY', dial: '60' },
  { name: 'Maldivas', code: 'MV', dial: '960' },
  { name: 'Mianmar', code: 'MM', dial: '95' },
  { name: 'Mongólia', code: 'MN', dial: '976' },
  { name: 'Nepal', code: 'NP', dial: '977' },
  { name: 'Omã', code: 'OM', dial: '968' },
  { name: 'Paquistão', code: 'PK', dial: '92' },
  { name: 'Palestina', code: 'PS', dial: '970' },
  { name: 'Quirguistão', code: 'KG', dial: '996' },
  { name: 'Singapura', code: 'SG', dial: '65' },
  { name: 'Síria', code: 'SY', dial: '963' },
  { name: 'Sri Lanka', code: 'LK', dial: '94' },
  { name: 'Tailândia', code: 'TH', dial: '66' },
  { name: 'Taiwan', code: 'TW', dial: '886' },
  { name: 'Tajiquistão', code: 'TJ', dial: '992' },
  { name: 'Timor-Leste', code: 'TL', dial: '670' },
  { name: 'Turcomenistão', code: 'TM', dial: '993' },
  { name: 'Turquia', code: 'TR', dial: '90' },
  { name: 'Uzbequistão', code: 'UZ', dial: '998' },
  { name: 'Vietnã', code: 'VN', dial: '84' },
  { name: 'Iêmen', code: 'YE', dial: '967' },

  // África
  { name: 'África do Sul', code: 'ZA', dial: '27' },
  { name: 'Angola', code: 'AO', dial: '244' },
  { name: 'Argélia', code: 'DZ', dial: '213' },
  { name: 'Benim', code: 'BJ', dial: '229' },
  { name: 'Botsuana', code: 'BW', dial: '267' },
  { name: 'Burkina Faso', code: 'BF', dial: '226' },
  { name: 'Burundi', code: 'BI', dial: '257' },
  { name: 'Cabo Verde', code: 'CV', dial: '238' },
  { name: 'Camarões', code: 'CM', dial: '237' },
  { name: 'Chade', code: 'TD', dial: '235' },
  { name: 'Comores', code: 'KM', dial: '269' },
  { name: 'Congo (Brazzaville)', code: 'CG', dial: '242' },
  { name: 'Congo (Kinshasa)', code: 'CD', dial: '243' },
  { name: 'Costa do Marfim', code: 'CI', dial: '225' },
  { name: 'Djibuti', code: 'DJ', dial: '253' },
  { name: 'Egito', code: 'EG', dial: '20' },
  { name: 'Eritreia', code: 'ER', dial: '291' },
  { name: 'Essuatíni', code: 'SZ', dial: '268' },
  { name: 'Etiópia', code: 'ET', dial: '251' },
  { name: 'Gabão', code: 'GA', dial: '241' },
  { name: 'Gâmbia', code: 'GM', dial: '220' },
  { name: 'Gana', code: 'GH', dial: '233' },
  { name: 'Guiné', code: 'GN', dial: '224' },
  { name: 'Guiné-Bissau', code: 'GW', dial: '245' },
  { name: 'Guiné Equatorial', code: 'GQ', dial: '240' },
  { name: 'Quênia', code: 'KE', dial: '254' },
  { name: 'Lesoto', code: 'LS', dial: '266' },
  { name: 'Libéria', code: 'LR', dial: '231' },
  { name: 'Líbia', code: 'LY', dial: '218' },
  { name: 'Madagascar', code: 'MG', dial: '261' },
  { name: 'Malawi', code: 'MW', dial: '265' },
  { name: 'Mali', code: 'ML', dial: '223' },
  { name: 'Marrocos', code: 'MA', dial: '212' },
  { name: 'Maurícia', code: 'MU', dial: '230' },
  { name: 'Mauritânia', code: 'MR', dial: '222' },
  { name: 'Moçambique', code: 'MZ', dial: '258' },
  { name: 'Namíbia', code: 'NA', dial: '264' },
  { name: 'Níger', code: 'NE', dial: '227' },
  { name: 'Nigéria', code: 'NG', dial: '234' },
  { name: 'Ruanda', code: 'RW', dial: '250' },
  { name: 'São Tomé e Príncipe', code: 'ST', dial: '239' },
  { name: 'Senegal', code: 'SN', dial: '221' },
  { name: 'Serra Leoa', code: 'SL', dial: '232' },
  { name: 'Seicheles', code: 'SC', dial: '248' },
  { name: 'Somália', code: 'SO', dial: '252' },
  { name: 'Sudão', code: 'SD', dial: '249' },
  { name: 'Sudão do Sul', code: 'SS', dial: '211' },
  { name: 'Tanzânia', code: 'TZ', dial: '255' },
  { name: 'Togo', code: 'TG', dial: '228' },
  { name: 'Tunísia', code: 'TN', dial: '216' },
  { name: 'Uganda', code: 'UG', dial: '256' },
  { name: 'Zâmbia', code: 'ZM', dial: '260' },
  { name: 'Zimbábue', code: 'ZW', dial: '263' },

  // Oceania
  { name: 'Austrália', code: 'AU', dial: '61' },
  { name: 'Fiji', code: 'FJ', dial: '679' },
  { name: 'Ilhas Marshall', code: 'MH', dial: '692' },
  { name: 'Ilhas Salomão', code: 'SB', dial: '677' },
  { name: 'Kiribati', code: 'KI', dial: '686' },
  { name: 'Micronésia', code: 'FM', dial: '691' },
  { name: 'Nauru', code: 'NR', dial: '674' },
  { name: 'Nova Zelândia', code: 'NZ', dial: '64' },
  { name: 'Palau', code: 'PW', dial: '680' },
  { name: 'Papua-Nova Guiné', code: 'PG', dial: '675' },
  { name: 'Samoa', code: 'WS', dial: '685' },
  { name: 'Tonga', code: 'TO', dial: '676' },
  { name: 'Tuvalu', code: 'TV', dial: '688' },
  { name: 'Vanuatu', code: 'VU', dial: '678' },
]

export const BRASIL = PAISES[0]
